PerWorldChat:
  enabled: true
  worlds:
    - test

PerWorldTabList:
  enabled: false

PerWorldCommands:
  enabled: true
  isWorldBlacklist: false
  globalBlockMessage: "&4Error: &fThis command is disabled, Sorry!"

  commands:
    example:
      - example

