PerWorldChat:
  enabled: true
  worlds:
    - test

PerWorldCommands:
  enabled: true
  isWorldBlacklist: false
  globalBlockMessage: "&4Error: &fThis command is disabled, Sorry!"

  commands:
    example:
      allowedWorlds:
        - example