name: PerWorldAll
version: '${version}'
main: net.tonimatasdev.perworldall.PerWorldAll
api-version: 1.19
authors: [ TonimatasDEV ]
description: Separe tablist per world
website: https://www.tonimatas.dev

commands:
  pwc:
    description: Main command.
permissions:
  pwc.reload:
    description: Allows player to use /pwc reload
  pwc.add:
    description: Allows player to use /pwc add <World name>
  pwc.command:
    description: Allows player to use /pwc
  pwc.remove:
    description: Allows player to use /pwc remove <World name>
