name: PerWorldAll
version: '${version}'
main: net.tonimatasdev.perworldall.PerWorldAll
api-version: 1.13
authors: [ TonimatasDEV ]
description: Set things for certain worlds
website: https://www.tonimatas.dev

commands:
  perworld:
    description: Primary command.

permissions:
  perworldall.*:
    description: All permissions of PerWorldAll
    children:
      - perworldall.admin
      - perworldall.perworldcommands

  perworldall.admin:
    description: Primary permossion.

  perworldall.perworldcommands.bypass:
    description: Permission for bypass command block.